### ISSUE TITLE
Addition of new Codeforces Question

### ISSUE THREAD

**Issue by anmolrajsoni15** [anupam-kumar-krishnan/Competitive_Programming#348]
Hello @anupam-kumar-krishnan, I would like to work on this issue. I am a competitive programmer and I have a good collection of codeforces question. So, please assign me this issue.
Thank You.

**Comment by anmolrajsoni15** [comment]
Sorry for interruption @anupam-kumar-krishnan can I directly generate PR on this issue ?

**Comment by anupam-kumar-krishnan** [comment]
Yes go ahead and raise a PR directly ✨🚀

**Comment by anmolrajsoni15** [comment]
Thanks
