### ISSUE TITLE
Implementation of Disjoint Set Union 

### ISSUE THREAD

**Issue by debapriya36** [anupam-kumar-krishnan/Competitive_Programming#358]
Hi @anupam-kumar-krishnan , i want to add code for DSU implementation in c++.
Can you please assign it to me ?

**Comment by anupam-kumar-krishnan** [comment]
There is nothing like assigned here
You can directly add the code in the respective folder
In short, raise a PR and it will be mereged after reviewing

Go ahead and raise a PR
For now I'm closing this issue
#hacktoberfest2022

**Comment by debapriya36** [comment]
okay :)
