### ISSUE TITLE
Submit few codes for Codeforces questions

### ISSUE THREAD

**Issue by amanmodiii** [anupam-kumar-krishnan/Competitive_Programming#368]
Hey @anupam-kumar-krishnan ,
I would like to provide solutions for some questions in Striver's CP sheet 
link : https://takeuforward.org/interview-experience/strivers-cp-sheet/?utm_source=youtube&utm_medium=striver&utm_campaign=yt_video

Could you label it under hacktoberfest ?
Regards.

**Comment by anupam-kumar-krishnan** [comment]
Yes go ahead and add the same
I'm closing this Issue here
You can directly raise a PR

**Comment by amanmodiii** [comment]
Should I make a seperate directory for Striver's CP sheet

**Comment by anupam-kumar-krishnan** [comment]
Yes just make a separate folder named Striver's SDE Sheet
