### ISSUE TITLE
Rotate Function Leetcode solution

### ISSUE THREAD

**Issue by ishita-0023** [anupam-kumar-krishnan/Competitive_Programming#404]
I want to contribute my python rotate function code which is on leetcode as a part of hacktoberfest 2022

**Comment by ishita-0023** [comment]
In which folder should i upload my solution?
it is a python solution of leetcode question (medium level)

**Comment by anupam-kumar-krishnan** [comment]
Commit your code in the folder named as Leetcode which is inside Coding Platforms folder
