### ISSUE TITLE
Triangle Of Numbers

### ISSUE THREAD

**Issue by Jainsuhani2021** [anupam-kumar-krishnan/Competitive_Programming#600]

**Comment by Jainsuhani2021** [comment]
Please assign this issue to me

**Comment by Jainsuhani2021** [comment]
https://github.com/anupam-kumar-krishnan/Competitive_Programming/pull/599#issue-1422911189
@anupam-kumar-krishnan 
sir please have a look

**Comment by anupam-kumar-krishnan** [comment]
No need to create an issue
You can directly raise a PR

**Comment by Jainsuhani2021** [comment]
ok thanku so much sir. Fron now onwards I will not create an issue
